name: Update gist with WakaTime stats
on:
  push:
    branches:
      - master
  schedule:
    - cron: "* * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: b83d2deb2e1ac2365c94a506e2d479ca
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIMEZONE: Asia/Seoul
